### ISSUE TITLE
Support merge queue branch protections

### ISSUE THREAD

**Issue by ehuss** [rust-lang/team#1735]
This is an issue to track adding [merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) branch protection support. This is **currently not possible** because it is not supported by GitHub's API. I figured it might be helpful to have an issue to track it nonetheless.

There are open requests for this at:
* https://github.com/orgs/community/discussions/50893
* https://github.com/orgs/community/discussions/77614

AFAIK, it *should* be OK for admins to manually set this even if the repo is managed in the team database. It looks like [`update_branch_protection`](https://github.com/rust-lang/sync-team/blob/9789ad2d5ac835c47cd2f84a828f16873b8ef760/src/github/api.rs#L587-L672) should be compatible. I have not tested this, yet, since all merge-queue repos I know of aren't tracked, yet.

**Comment by amustaque97** [comment]
- Concepts & constraints
  - Branch protection rules (classic) now have a checkbox “Require merge queue”, but the public REST branches/branch-protection API does not expose a merge queue flag.​
  - GraphQL createBranchProtectionRule/updateBranchProtectionRule also do not support merge queue options yet (GitHub community discussion confirms this).​

- Rulesets do support Merge queue behaviour: merge method, min/max group size, build concurrency, status‑check behaviour, etc
Github API link: https://docs.github.com/en/rest/repos/rules?apiVersion=2022-11-28#create-a-repository-ruleset

<img width="1512" height="982" alt="Image" src="https://github.com/user-attachments/assets/41855a70-19e4-4d5a-9cd2-2bdcbce5731a" />


If we plan migration from `[[branch-protections]]` to `rulesets`, this should be doable. If we all agree, I can propose subcommand changes (`[[branch-protections]]` to `rulesets`). After migration, we can enable merge queues. 

I would love to hear your thoughts.

**Comment by Kobzol** [comment]
The main required thing for that is to reimplement the branch config from protections to rulesets in `team`. Although we might want to do that in parts and support both protections and rulesets for some time, because changing everything from protections to rulesets at once seems scary (maybe we could do an allowlist of a few repos where we will use rulesets though).

**Comment by amustaque97** [comment]
> reimplement the branch config from protections to rulesets in `team`

To begin with, I will create the PR that will replicate the branch protection to rulesets with the merge queues.

Do you have any repos in mind to start with?

**Comment by Kobzol** [comment]
E.g. `rust-lang/bors`, it has relatively fast CI and it wouldn't matter if its queue gets blocked for a short time.

**Comment by marcoieni** [comment]
I agree an allow list of repos is the best approach to start with 👍

**Comment by marcoieni** [comment]
I took screenshots of all the GitHub branch protections settings and with OCR I found what repositories have merge queue enabled. Here's the list:

```toml
[[branch_protections]]
repo = "rust-lang/ci-mirrors"
name = "main"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 1, min_pull_requests_to_merge = 1, min_wait_minutes = 1, max_pull_requests_to_merge = 15, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/crater"
name = "master"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/crates-io-auth-action"
name = "main"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/edition-guide"
name = "master"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/fls"
name = "main"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 1, min_pull_requests_to_merge = 1, min_wait_minutes = 1, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/gha-self-hosted"
name = "main"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 1, min_pull_requests_to_merge = 1, min_wait_minutes = 1, max_pull_requests_to_merge = 1, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/git2-rs"
name = "master"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 1, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/hashbrown"
name = "master"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/libc"
name = "main"
merge_queue = { enabled = true, merge_method = "Rebase and merge", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/libc"
name = "libc-0.2"
merge_queue = { enabled = true, merge_method = "Rebase and merge", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/mdbook"
name = "master"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 1, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/measureme"
name = "master"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/miri"
name = "master"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/miri-test-libstd"
name = "master"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/nomicon"
name = "master"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/reference"
name = "master"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/rust-analyzer"
name = "master"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/rust-bindgen"
name = "main"
merge_queue = { enabled = true, merge_method = "Rebase and merge", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/rust-clippy"
name = "master"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/rustc-perf"
name = "master"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/rustup"
name = "main"
merge_queue = { enabled = true, merge_method = "Rebase and merge", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/stdarch"
name = "main"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/team"
name = "main"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 1, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 1, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/triagebot"
name = "master"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }
```

- [ ] Manually verify the data of the toml above
- [ ] Check zulip conversations to check if we missed some repo
- [ ] Add support for all these fields (make them configurable via team), maybe with a [merge_queue] section inside the branch protection
- [ ] Convert these repos to rulesets.

**Comment by Kobzol** [comment]
I don't think that most of those repos actually need multi-PR merging. So if it makes things easier, defaulting to one PR per merge might simplify the team config.

**Comment by marcoieni** [comment]
Updated list after removing the repositories added in https://github.com/rust-lang/team/pull/2350:
```toml
[[branch_protections]]
repo = "rust-lang/ci-mirrors"
name = "main"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 1, min_pull_requests_to_merge = 1, min_wait_minutes = 1, max_pull_requests_to_merge = 15, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/fls"
name = "main"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 1, min_pull_requests_to_merge = 1, min_wait_minutes = 1, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/gha-self-hosted"
name = "main"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 1, min_pull_requests_to_merge = 1, min_wait_minutes = 1, max_pull_requests_to_merge = 1, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/git2-rs"
name = "master"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 1, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/libc"
name = "main"
merge_queue = { enabled = true, merge_method = "Rebase and merge", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/libc"
name = "libc-0.2"
merge_queue = { enabled = true, merge_method = "Rebase and merge", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/mdbook"
name = "master"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 1, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/miri-test-libstd"
name = "master"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 120 }

[[branch_protections]]
repo = "rust-lang/rust-bindgen"
name = "main"
merge_queue = { enabled = true, merge_method = "Rebase and merge", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/rustup"
name = "main"
merge_queue = { enabled = true, merge_method = "Rebase and merge", max_pull_requests_to_build = 5, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 5, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }

[[branch_protections]]
repo = "rust-lang/team"
name = "main"
merge_queue = { enabled = true, merge_method = "Merge commit", max_pull_requests_to_build = 1, min_pull_requests_to_merge = 1, min_wait_minutes = 5, max_pull_requests_to_merge = 1, only_merge_non_failing_pull_requests = true, status_check_timeout_minutes = 60 }
```

Note that `rust-lang/miri-test-libstd` had an error in the config taken with the OCR which I fixed.
